// Code generated by MockGen. DO NOT EDIT.
// Source: comment_history.go
//
// Generated by this command:
//
//	mockgen -source=comment_history.go -destination=mock_domain/mock_comment_history_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentHistoryRepository is a mock of CommentHistoryRepository interface.
type MockCommentHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommentHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCommentHistoryRepositoryMockRecorder is the mock recorder for MockCommentHistoryRepository.
type MockCommentHistoryRepositoryMockRecorder struct {
	mock *MockCommentHistoryRepository
}

// NewMockCommentHistoryRepository creates a new mock instance.
func NewMockCommentHistoryRepository(ctrl *gomock.Controller) *MockCommentHistoryRepository {
	mock := &MockCommentHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockCommentHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentHistoryRepository) EXPECT() *MockCommentHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentHistoryRepository) Create(ctx context.Context, history domain.CommentHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCommentHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentHistoryRepository)(nil).Create), ctx, history)
}
