// Code generated by MockGen. DO NOT EDIT.
// Source: case.go
//
// Generated by this command:
//
//	mockgen -source=case.go -destination=mock_domain/mock_case_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCaseRepository is a mock of CaseRepository interface.
type MockCaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCaseRepositoryMockRecorder
	isgomock struct{}
}

// MockCaseRepositoryMockRecorder is the mock recorder for MockCaseRepository.
type MockCaseRepositoryMockRecorder struct {
	mock *MockCaseRepository
}

// NewMockCaseRepository creates a new mock instance.
func NewMockCaseRepository(ctrl *gomock.Controller) *MockCaseRepository {
	mock := &MockCaseRepository{ctrl: ctrl}
	mock.recorder = &MockCaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseRepository) EXPECT() *MockCaseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCaseRepository) Create(ctx context.Context, crmCase domain.Case) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, crmCase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCaseRepositoryMockRecorder) Create(ctx, crmCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCaseRepository)(nil).Create), ctx, crmCase)
}

// CreateBatch mocks base method.
func (m *MockCaseRepository) CreateBatch(ctx context.Context, cases []domain.Case) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, cases)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockCaseRepositoryMockRecorder) CreateBatch(ctx, cases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockCaseRepository)(nil).CreateBatch), ctx, cases)
}

// GetByID mocks base method.
func (m *MockCaseRepository) GetByID(ctx context.Context, caseID string) (*domain.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, caseID)
	ret0, _ := ret[0].(*domain.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCaseRepositoryMockRecorder) GetByID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCaseRepository)(nil).GetByID), ctx, caseID)
}

// Search mocks base method.
func (m *MockCaseRepository) Search(ctx context.Context, filters domain.CaseFilters) (domain.PagingResult[domain.Case], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Case])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCaseRepositoryMockRecorder) Search(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCaseRepository)(nil).Search), ctx, filters)
}

// SearchFull mocks base method.
func (m *MockCaseRepository) SearchFull(ctx context.Context, filters domain.CaseFilters) (domain.PagingResult[domain.CaseFull], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFull", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.CaseFull])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFull indicates an expected call of SearchFull.
func (mr *MockCaseRepositoryMockRecorder) SearchFull(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFull", reflect.TypeOf((*MockCaseRepository)(nil).SearchFull), ctx, filters)
}

// Update mocks base method.
func (m *MockCaseRepository) Update(ctx context.Context, crmCase domain.Case) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, crmCase)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCaseRepositoryMockRecorder) Update(ctx, crmCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCaseRepository)(nil).Update), ctx, crmCase)
}
