// Code generated by MockGen. DO NOT EDIT.
// Source: case_history.go
//
// Generated by this command:
//
//	mockgen -source=case_history.go -destination=mock_domain/mock_case_history_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCaseHistoryRepository is a mock of CaseHistoryRepository interface.
type MockCaseHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCaseHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCaseHistoryRepositoryMockRecorder is the mock recorder for MockCaseHistoryRepository.
type MockCaseHistoryRepositoryMockRecorder struct {
	mock *MockCaseHistoryRepository
}

// NewMockCaseHistoryRepository creates a new mock instance.
func NewMockCaseHistoryRepository(ctrl *gomock.Controller) *MockCaseHistoryRepository {
	mock := &MockCaseHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockCaseHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseHistoryRepository) EXPECT() *MockCaseHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCaseHistoryRepository) Create(ctx context.Context, history domain.CaseHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCaseHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCaseHistoryRepository)(nil).Create), ctx, history)
}

// GetByCaseID mocks base method.
func (m *MockCaseHistoryRepository) GetByCaseID(ctx context.Context, caseID string) ([]domain.CaseHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCaseID", ctx, caseID)
	ret0, _ := ret[0].([]domain.CaseHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCaseID indicates an expected call of GetByCaseID.
func (mr *MockCaseHistoryRepositoryMockRecorder) GetByCaseID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCaseID", reflect.TypeOf((*MockCaseHistoryRepository)(nil).GetByCaseID), ctx, caseID)
}
