// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/queue.go -destination=internal/domain/mock_domain/mock_queue_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRepository is a mock of QueueRepository interface.
type MockQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockQueueRepositoryMockRecorder is the mock recorder for MockQueueRepository.
type MockQueueRepositoryMockRecorder struct {
	mock *MockQueueRepository
}

// NewMockQueueRepository creates a new mock instance.
func NewMockQueueRepository(ctrl *gomock.Controller) *MockQueueRepository {
	mock := &MockQueueRepository{ctrl: ctrl}
	mock.recorder = &MockQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRepository) EXPECT() *MockQueueRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockQueueRepository) AddMember(ctx context.Context, queueID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, queueID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockQueueRepositoryMockRecorder) AddMember(ctx, queueID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockQueueRepository)(nil).AddMember), ctx, queueID, userID)
}

// Create mocks base method.
func (m *MockQueueRepository) Create(ctx context.Context, queue domain.Queue) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, queue)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockQueueRepositoryMockRecorder) Create(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQueueRepository)(nil).Create), ctx, queue)
}

// Delete mocks base method.
func (m *MockQueueRepository) Delete(ctx context.Context, queueID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, queueID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueueRepositoryMockRecorder) Delete(ctx, queueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueueRepository)(nil).Delete), ctx, queueID)
}

// GetByID mocks base method.
func (m *MockQueueRepository) GetByID(ctx context.Context, queueID string) (*domain.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, queueID)
	ret0, _ := ret[0].(*domain.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockQueueRepositoryMockRecorder) GetByID(ctx, queueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockQueueRepository)(nil).GetByID), ctx, queueID)
}

// GetMembers mocks base method.
func (m *MockQueueRepository) GetMembers(ctx context.Context, queueID string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, queueID)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockQueueRepositoryMockRecorder) GetMembers(ctx, queueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockQueueRepository)(nil).GetMembers), ctx, queueID)
}

// GetQueuesByUser mocks base method.
func (m *MockQueueRepository) GetQueuesByUser(ctx context.Context, userID string) ([]domain.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueuesByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueuesByUser indicates an expected call of GetQueuesByUser.
func (mr *MockQueueRepositoryMockRecorder) GetQueuesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueuesByUser", reflect.TypeOf((*MockQueueRepository)(nil).GetQueuesByUser), ctx, userID)
}

// RemoveMember mocks base method.
func (m *MockQueueRepository) RemoveMember(ctx context.Context, queueID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, queueID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockQueueRepositoryMockRecorder) RemoveMember(ctx, queueID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockQueueRepository)(nil).RemoveMember), ctx, queueID, userID)
}

// Search mocks base method.
func (m *MockQueueRepository) Search(ctx context.Context, filters domain.QueueFilters) (domain.PagingResult[domain.Queue], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Queue])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockQueueRepositoryMockRecorder) Search(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockQueueRepository)(nil).Search), ctx, filters)
}

// Update mocks base method.
func (m *MockQueueRepository) Update(ctx context.Context, queue domain.Queue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, queue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQueueRepositoryMockRecorder) Update(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQueueRepository)(nil).Update), ctx, queue)
}
