// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/icrxz/crm-api-core/internal/domain (interfaces: PartnerRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_domain/partner_repository.go . PartnerRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPartnerRepository is a mock of PartnerRepository interface.
type MockPartnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerRepositoryMockRecorder is the mock recorder for MockPartnerRepository.
type MockPartnerRepositoryMockRecorder struct {
	mock *MockPartnerRepository
}

// NewMockPartnerRepository creates a new mock instance.
func NewMockPartnerRepository(ctrl *gomock.Controller) *MockPartnerRepository {
	mock := &MockPartnerRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerRepository) EXPECT() *MockPartnerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPartnerRepository) Create(ctx context.Context, partner domain.Partner) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, partner)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPartnerRepositoryMockRecorder) Create(ctx, partner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPartnerRepository)(nil).Create), ctx, partner)
}

// CreateBatch mocks base method.
func (m *MockPartnerRepository) CreateBatch(ctx context.Context, partners []domain.Partner) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, partners)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockPartnerRepositoryMockRecorder) CreateBatch(ctx, partners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockPartnerRepository)(nil).CreateBatch), ctx, partners)
}

// Delete mocks base method.
func (m *MockPartnerRepository) Delete(ctx context.Context, partnerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, partnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPartnerRepositoryMockRecorder) Delete(ctx, partnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPartnerRepository)(nil).Delete), ctx, partnerID)
}

// GetByID mocks base method.
func (m *MockPartnerRepository) GetByID(ctx context.Context, partnerID string) (*domain.Partner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, partnerID)
	ret0, _ := ret[0].(*domain.Partner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPartnerRepositoryMockRecorder) GetByID(ctx, partnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPartnerRepository)(nil).GetByID), ctx, partnerID)
}

// Search mocks base method.
func (m *MockPartnerRepository) Search(ctx context.Context, filters domain.PartnerFilters) (domain.PagingResult[domain.Partner], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Partner])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPartnerRepositoryMockRecorder) Search(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPartnerRepository)(nil).Search), ctx, filters)
}

// Update mocks base method.
func (m *MockPartnerRepository) Update(ctx context.Context, partnerToUpdate domain.Partner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, partnerToUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPartnerRepositoryMockRecorder) Update(ctx, partnerToUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPartnerRepository)(nil).Update), ctx, partnerToUpdate)
}
