// Code generated by MockGen. DO NOT EDIT.
// Source: comment_service.go
//
// Generated by this command:
//
//	mockgen -source=comment_service.go -destination=mock_application/mock_comment_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
	isgomock struct{}
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentService) Create(ctx context.Context, comment domain.Comment) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, comment)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentServiceMockRecorder) Create(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentService)(nil).Create), ctx, comment)
}

// DeleteByCaseID mocks base method.
func (m *MockCommentService) DeleteByCaseID(ctx context.Context, caseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCaseID", ctx, caseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCaseID indicates an expected call of DeleteByCaseID.
func (mr *MockCommentServiceMockRecorder) DeleteByCaseID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCaseID", reflect.TypeOf((*MockCommentService)(nil).DeleteByCaseID), ctx, caseID)
}

// GetByCaseID mocks base method.
func (m *MockCommentService) GetByCaseID(ctx context.Context, caseID string) ([]domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCaseID", ctx, caseID)
	ret0, _ := ret[0].([]domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCaseID indicates an expected call of GetByCaseID.
func (mr *MockCommentServiceMockRecorder) GetByCaseID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCaseID", reflect.TypeOf((*MockCommentService)(nil).GetByCaseID), ctx, caseID)
}

// GetByID mocks base method.
func (m *MockCommentService) GetByID(ctx context.Context, commentID string) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, commentID)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentServiceMockRecorder) GetByID(ctx, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentService)(nil).GetByID), ctx, commentID)
}
