// Code generated by MockGen. DO NOT EDIT.
// Source: attachments_service.go
//
// Generated by this command:
//
//	mockgen -source=attachments_service.go -destination=mock_application/mock_attachments_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachmentService is a mock of AttachmentService interface.
type MockAttachmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentServiceMockRecorder
	isgomock struct{}
}

// MockAttachmentServiceMockRecorder is the mock recorder for MockAttachmentService.
type MockAttachmentServiceMockRecorder struct {
	mock *MockAttachmentService
}

// NewMockAttachmentService creates a new mock instance.
func NewMockAttachmentService(ctrl *gomock.Controller) *MockAttachmentService {
	mock := &MockAttachmentService{ctrl: ctrl}
	mock.recorder = &MockAttachmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentService) EXPECT() *MockAttachmentServiceMockRecorder {
	return m.recorder
}

// DeleteByComments mocks base method.
func (m *MockAttachmentService) DeleteByComments(ctx context.Context, commentIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByComments", ctx, commentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByComments indicates an expected call of DeleteByComments.
func (mr *MockAttachmentServiceMockRecorder) DeleteByComments(ctx, commentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByComments", reflect.TypeOf((*MockAttachmentService)(nil).DeleteByComments), ctx, commentIDs)
}

// GetByID mocks base method.
func (m *MockAttachmentService) GetByID(ctx context.Context, attachmentID string) (*domain.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, attachmentID)
	ret0, _ := ret[0].(*domain.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAttachmentServiceMockRecorder) GetByID(ctx, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAttachmentService)(nil).GetByID), ctx, attachmentID)
}

// SearchByCommentID mocks base method.
func (m *MockAttachmentService) SearchByCommentID(ctx context.Context, commentID string) ([]domain.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByCommentID", ctx, commentID)
	ret0, _ := ret[0].([]domain.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByCommentID indicates an expected call of SearchByCommentID.
func (mr *MockAttachmentServiceMockRecorder) SearchByCommentID(ctx, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByCommentID", reflect.TypeOf((*MockAttachmentService)(nil).SearchByCommentID), ctx, commentID)
}
