// Code generated by MockGen. DO NOT EDIT.
// Source: case_service.go
//
// Generated by this command:
//
//	mockgen -source=case_service.go -destination=mock_application/mock_case_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCaseService is a mock of CaseService interface.
type MockCaseService struct {
	ctrl     *gomock.Controller
	recorder *MockCaseServiceMockRecorder
	isgomock struct{}
}

// MockCaseServiceMockRecorder is the mock recorder for MockCaseService.
type MockCaseServiceMockRecorder struct {
	mock *MockCaseService
}

// NewMockCaseService creates a new mock instance.
func NewMockCaseService(ctrl *gomock.Controller) *MockCaseService {
	mock := &MockCaseService{ctrl: ctrl}
	mock.recorder = &MockCaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseService) EXPECT() *MockCaseServiceMockRecorder {
	return m.recorder
}

// CreateCase mocks base method.
func (m *MockCaseService) CreateCase(ctx context.Context, newCase domain.CreateCase) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCase", ctx, newCase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCase indicates an expected call of CreateCase.
func (mr *MockCaseServiceMockRecorder) CreateCase(ctx, newCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCase", reflect.TypeOf((*MockCaseService)(nil).CreateCase), ctx, newCase)
}

// GetCaseByID mocks base method.
func (m *MockCaseService) GetCaseByID(ctx context.Context, caseID string) (*domain.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseByID", ctx, caseID)
	ret0, _ := ret[0].(*domain.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseByID indicates an expected call of GetCaseByID.
func (mr *MockCaseServiceMockRecorder) GetCaseByID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseByID", reflect.TypeOf((*MockCaseService)(nil).GetCaseByID), ctx, caseID)
}

// GetCaseFullByID mocks base method.
func (m *MockCaseService) GetCaseFullByID(ctx context.Context, caseID string) (*domain.CaseFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseFullByID", ctx, caseID)
	ret0, _ := ret[0].(*domain.CaseFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseFullByID indicates an expected call of GetCaseFullByID.
func (mr *MockCaseServiceMockRecorder) GetCaseFullByID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseFullByID", reflect.TypeOf((*MockCaseService)(nil).GetCaseFullByID), ctx, caseID)
}

// SearchCases mocks base method.
func (m *MockCaseService) SearchCases(ctx context.Context, filters domain.CaseFilters) (domain.PagingResult[domain.Case], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCases", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Case])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCases indicates an expected call of SearchCases.
func (mr *MockCaseServiceMockRecorder) SearchCases(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCases", reflect.TypeOf((*MockCaseService)(nil).SearchCases), ctx, filters)
}

// SearchCasesFull mocks base method.
func (m *MockCaseService) SearchCasesFull(ctx context.Context, filters domain.CaseFilters) (domain.PagingResult[domain.CaseFull], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCasesFull", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.CaseFull])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCasesFull indicates an expected call of SearchCasesFull.
func (mr *MockCaseServiceMockRecorder) SearchCasesFull(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCasesFull", reflect.TypeOf((*MockCaseService)(nil).SearchCasesFull), ctx, filters)
}

// UpdateCase mocks base method.
func (m *MockCaseService) UpdateCase(ctx context.Context, caseID string, newCase domain.CaseUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCase", ctx, caseID, newCase)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCase indicates an expected call of UpdateCase.
func (mr *MockCaseServiceMockRecorder) UpdateCase(ctx, caseID, newCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCase", reflect.TypeOf((*MockCaseService)(nil).UpdateCase), ctx, caseID, newCase)
}
