// Code generated by MockGen. DO NOT EDIT.
// Source: case_actions_service.go
//
// Generated by this command:
//
//	mockgen -source=case_actions_service.go -destination=mock_application/mock_case_actions_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCaseActionService is a mock of CaseActionService interface.
type MockCaseActionService struct {
	ctrl     *gomock.Controller
	recorder *MockCaseActionServiceMockRecorder
	isgomock struct{}
}

// MockCaseActionServiceMockRecorder is the mock recorder for MockCaseActionService.
type MockCaseActionServiceMockRecorder struct {
	mock *MockCaseActionService
}

// NewMockCaseActionService creates a new mock instance.
func NewMockCaseActionService(ctrl *gomock.Controller) *MockCaseActionService {
	mock := &MockCaseActionService{ctrl: ctrl}
	mock.recorder = &MockCaseActionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseActionService) EXPECT() *MockCaseActionServiceMockRecorder {
	return m.recorder
}

// ChangeOwner mocks base method.
func (m *MockCaseActionService) ChangeOwner(ctx context.Context, caseID string, newOwner domain.ChangeOwner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeOwner", ctx, caseID, newOwner)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeOwner indicates an expected call of ChangeOwner.
func (mr *MockCaseActionServiceMockRecorder) ChangeOwner(ctx, caseID, newOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeOwner", reflect.TypeOf((*MockCaseActionService)(nil).ChangeOwner), ctx, caseID, newOwner)
}

// ChangePartner mocks base method.
func (m *MockCaseActionService) ChangePartner(ctx context.Context, caseID string, newPartner domain.ChangePartner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePartner", ctx, caseID, newPartner)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePartner indicates an expected call of ChangePartner.
func (mr *MockCaseActionServiceMockRecorder) ChangePartner(ctx, caseID, newPartner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePartner", reflect.TypeOf((*MockCaseActionService)(nil).ChangePartner), ctx, caseID, newPartner)
}

// ChangeStatus mocks base method.
func (m *MockCaseActionService) ChangeStatus(ctx context.Context, caseID string, newStatus domain.ChangeStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatus", ctx, caseID, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeStatus indicates an expected call of ChangeStatus.
func (mr *MockCaseActionServiceMockRecorder) ChangeStatus(ctx, caseID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatus", reflect.TypeOf((*MockCaseActionService)(nil).ChangeStatus), ctx, caseID, newStatus)
}

// GenerateReport mocks base method.
func (m *MockCaseActionService) GenerateReport(ctx context.Context, caseID string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateReport", ctx, caseID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateReport indicates an expected call of GenerateReport.
func (mr *MockCaseActionServiceMockRecorder) GenerateReport(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateReport", reflect.TypeOf((*MockCaseActionService)(nil).GenerateReport), ctx, caseID)
}

// ResetCaseStatus mocks base method.
func (m *MockCaseActionService) ResetCaseStatus(ctx context.Context, caseID, author string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetCaseStatus", ctx, caseID, author)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetCaseStatus indicates an expected call of ResetCaseStatus.
func (mr *MockCaseActionServiceMockRecorder) ResetCaseStatus(ctx, caseID, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetCaseStatus", reflect.TypeOf((*MockCaseActionService)(nil).ResetCaseStatus), ctx, caseID, author)
}
