// Code generated by MockGen. DO NOT EDIT.
// Source: contractor_service.go
//
// Generated by this command:
//
//	mockgen -source=contractor_service.go -destination=mock_application/mock_contractor_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockContractorService is a mock of ContractorService interface.
type MockContractorService struct {
	ctrl     *gomock.Controller
	recorder *MockContractorServiceMockRecorder
	isgomock struct{}
}

// MockContractorServiceMockRecorder is the mock recorder for MockContractorService.
type MockContractorServiceMockRecorder struct {
	mock *MockContractorService
}

// NewMockContractorService creates a new mock instance.
func NewMockContractorService(ctrl *gomock.Controller) *MockContractorService {
	mock := &MockContractorService{ctrl: ctrl}
	mock.recorder = &MockContractorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractorService) EXPECT() *MockContractorServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContractorService) Create(ctx context.Context, contractor domain.Contractor) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, contractor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContractorServiceMockRecorder) Create(ctx, contractor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContractorService)(nil).Create), ctx, contractor)
}

// Delete mocks base method.
func (m *MockContractorService) Delete(ctx context.Context, contractorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, contractorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContractorServiceMockRecorder) Delete(ctx, contractorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContractorService)(nil).Delete), ctx, contractorID)
}

// GetByID mocks base method.
func (m *MockContractorService) GetByID(ctx context.Context, contractorID string) (*domain.Contractor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, contractorID)
	ret0, _ := ret[0].(*domain.Contractor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockContractorServiceMockRecorder) GetByID(ctx, contractorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockContractorService)(nil).GetByID), ctx, contractorID)
}

// Search mocks base method.
func (m *MockContractorService) Search(ctx context.Context, filters domain.ContractorFilters) (domain.PagingResult[domain.Contractor], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Contractor])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockContractorServiceMockRecorder) Search(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockContractorService)(nil).Search), ctx, filters)
}

// Update mocks base method.
func (m *MockContractorService) Update(ctx context.Context, contractorID string, contractor domain.UpdateContractor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, contractorID, contractor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockContractorServiceMockRecorder) Update(ctx, contractorID, contractor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContractorService)(nil).Update), ctx, contractorID, contractor)
}
