// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_service.go
//
// Generated by this command:
//
//	mockgen -source=transaction_service.go -destination=mock_application/mock_transaction_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
	isgomock struct{}
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionService) CreateTransaction(ctx context.Context, transaction domain.Transaction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, transaction)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionServiceMockRecorder) CreateTransaction(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionService)(nil).CreateTransaction), ctx, transaction)
}

// CreateTransactionBatch mocks base method.
func (m *MockTransactionService) CreateTransactionBatch(ctx context.Context, transactions []domain.Transaction) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionBatch", ctx, transactions)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionBatch indicates an expected call of CreateTransactionBatch.
func (mr *MockTransactionServiceMockRecorder) CreateTransactionBatch(ctx, transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionBatch", reflect.TypeOf((*MockTransactionService)(nil).CreateTransactionBatch), ctx, transactions)
}

// DeleteByCaseID mocks base method.
func (m *MockTransactionService) DeleteByCaseID(ctx context.Context, caseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCaseID", ctx, caseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCaseID indicates an expected call of DeleteByCaseID.
func (mr *MockTransactionServiceMockRecorder) DeleteByCaseID(ctx, caseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCaseID", reflect.TypeOf((*MockTransactionService)(nil).DeleteByCaseID), ctx, caseID)
}

// GetTransaction mocks base method.
func (m *MockTransactionService) GetTransaction(ctx context.Context, transactionID string) (domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, transactionID)
	ret0, _ := ret[0].(domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionServiceMockRecorder) GetTransaction(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionService)(nil).GetTransaction), ctx, transactionID)
}

// SearchTransactions mocks base method.
func (m *MockTransactionService) SearchTransactions(ctx context.Context, filters domain.TransactionFilters) ([]domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTransactions", ctx, filters)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTransactions indicates an expected call of SearchTransactions.
func (mr *MockTransactionServiceMockRecorder) SearchTransactions(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTransactions", reflect.TypeOf((*MockTransactionService)(nil).SearchTransactions), ctx, filters)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionService) UpdateTransaction(ctx context.Context, transactionID string, transactionUpdate domain.TransactionUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", ctx, transactionID, transactionUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionServiceMockRecorder) UpdateTransaction(ctx, transactionID, transactionUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionService)(nil).UpdateTransaction), ctx, transactionID, transactionUpdate)
}
