// Code generated by MockGen. DO NOT EDIT.
// Source: batch_case_service.go
//
// Generated by this command:
//
//	mockgen -source=batch_case_service.go -destination=mock_application/mock_batch_case_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBatchCaseService is a mock of BatchCaseService interface.
type MockBatchCaseService struct {
	ctrl     *gomock.Controller
	recorder *MockBatchCaseServiceMockRecorder
	isgomock struct{}
}

// MockBatchCaseServiceMockRecorder is the mock recorder for MockBatchCaseService.
type MockBatchCaseServiceMockRecorder struct {
	mock *MockBatchCaseService
}

// NewMockBatchCaseService creates a new mock instance.
func NewMockBatchCaseService(ctrl *gomock.Controller) *MockBatchCaseService {
	mock := &MockBatchCaseService{ctrl: ctrl}
	mock.recorder = &MockBatchCaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchCaseService) EXPECT() *MockBatchCaseServiceMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockBatchCaseService) CreateBatch(ctx context.Context, file io.Reader, fileName, createdBy, company string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, file, fileName, createdBy, company)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockBatchCaseServiceMockRecorder) CreateBatch(ctx, file, fileName, createdBy, company any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockBatchCaseService)(nil).CreateBatch), ctx, file, fileName, createdBy, company)
}
