// Code generated by MockGen. DO NOT EDIT.
// Source: report_service.go
//
// Generated by this command:
//
//	mockgen -source=report_service.go -destination=mock_application/mock_report_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReportService is a mock of ReportService interface.
type MockReportService struct {
	ctrl     *gomock.Controller
	recorder *MockReportServiceMockRecorder
	isgomock struct{}
}

// MockReportServiceMockRecorder is the mock recorder for MockReportService.
type MockReportServiceMockRecorder struct {
	mock *MockReportService
}

// NewMockReportService creates a new mock instance.
func NewMockReportService(ctrl *gomock.Controller) *MockReportService {
	mock := &MockReportService{ctrl: ctrl}
	mock.recorder = &MockReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportService) EXPECT() *MockReportServiceMockRecorder {
	return m.recorder
}

// GenerateReport mocks base method.
func (m *MockReportService) GenerateReport(ctx context.Context, crmCase domain.Case) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateReport", ctx, crmCase)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateReport indicates an expected call of GenerateReport.
func (mr *MockReportServiceMockRecorder) GenerateReport(ctx, crmCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateReport", reflect.TypeOf((*MockReportService)(nil).GenerateReport), ctx, crmCase)
}
