// Code generated by MockGen. DO NOT EDIT.
// Source: queue_service.go
//
// Generated by this command:
//
//	mockgen -source=queue_service.go -destination=mock_application/mock_queue_service.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueService is a mock of QueueService interface.
type MockQueueService struct {
	ctrl     *gomock.Controller
	recorder *MockQueueServiceMockRecorder
	isgomock struct{}
}

// MockQueueServiceMockRecorder is the mock recorder for MockQueueService.
type MockQueueServiceMockRecorder struct {
	mock *MockQueueService
}

// NewMockQueueService creates a new mock instance.
func NewMockQueueService(ctrl *gomock.Controller) *MockQueueService {
	mock := &MockQueueService{ctrl: ctrl}
	mock.recorder = &MockQueueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueService) EXPECT() *MockQueueServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockQueueService) AddMember(ctx context.Context, queueID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, queueID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockQueueServiceMockRecorder) AddMember(ctx, queueID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockQueueService)(nil).AddMember), ctx, queueID, userID)
}

// Create mocks base method.
func (m *MockQueueService) Create(ctx context.Context, queue domain.Queue) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, queue)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockQueueServiceMockRecorder) Create(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQueueService)(nil).Create), ctx, queue)
}

// Delete mocks base method.
func (m *MockQueueService) Delete(ctx context.Context, queueID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, queueID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueueServiceMockRecorder) Delete(ctx, queueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueueService)(nil).Delete), ctx, queueID)
}

// GetByID mocks base method.
func (m *MockQueueService) GetByID(ctx context.Context, queueID string) (*domain.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, queueID)
	ret0, _ := ret[0].(*domain.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockQueueServiceMockRecorder) GetByID(ctx, queueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockQueueService)(nil).GetByID), ctx, queueID)
}

// GetMembers mocks base method.
func (m *MockQueueService) GetMembers(ctx context.Context, queueID string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, queueID)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockQueueServiceMockRecorder) GetMembers(ctx, queueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockQueueService)(nil).GetMembers), ctx, queueID)
}

// GetQueuesByUser mocks base method.
func (m *MockQueueService) GetQueuesByUser(ctx context.Context, userID string) ([]domain.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueuesByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueuesByUser indicates an expected call of GetQueuesByUser.
func (mr *MockQueueServiceMockRecorder) GetQueuesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueuesByUser", reflect.TypeOf((*MockQueueService)(nil).GetQueuesByUser), ctx, userID)
}

// RemoveMember mocks base method.
func (m *MockQueueService) RemoveMember(ctx context.Context, queueID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, queueID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockQueueServiceMockRecorder) RemoveMember(ctx, queueID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockQueueService)(nil).RemoveMember), ctx, queueID, userID)
}

// Search mocks base method.
func (m *MockQueueService) Search(ctx context.Context, filters domain.QueueFilters) (domain.PagingResult[domain.Queue], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Queue])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockQueueServiceMockRecorder) Search(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockQueueService)(nil).Search), ctx, filters)
}

// Update mocks base method.
func (m *MockQueueService) Update(ctx context.Context, queueID string, update domain.UpdateQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, queueID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQueueServiceMockRecorder) Update(ctx, queueID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQueueService)(nil).Update), ctx, queueID, update)
}
