// Code generated by MockGen. DO NOT EDIT.
// Source: queue_resolver.go
//
// Generated by this command:
//
//	mockgen -source=queue_resolver.go -destination=mock_application/mock_queue_resolver.go -package=mock_application
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueResolver is a mock of QueueResolver interface.
type MockQueueResolver struct {
	ctrl     *gomock.Controller
	recorder *MockQueueResolverMockRecorder
	isgomock struct{}
}

// MockQueueResolverMockRecorder is the mock recorder for MockQueueResolver.
type MockQueueResolverMockRecorder struct {
	mock *MockQueueResolver
}

// NewMockQueueResolver creates a new mock instance.
func NewMockQueueResolver(ctrl *gomock.Controller) *MockQueueResolver {
	mock := &MockQueueResolver{ctrl: ctrl}
	mock.recorder = &MockQueueResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueResolver) EXPECT() *MockQueueResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockQueueResolver) Resolve(ctx context.Context, crmCase domain.Case) (*domain.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, crmCase)
	ret0, _ := ret[0].(*domain.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockQueueResolverMockRecorder) Resolve(ctx, crmCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockQueueResolver)(nil).Resolve), ctx, crmCase)
}
