// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/icrxz/crm-api-core/internal/application (interfaces: PartnerService)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mock_application/partner_service.go -package=mock_application github.com/icrxz/crm-api-core/internal/application PartnerService
//

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/icrxz/crm-api-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPartnerService is a mock of PartnerService interface.
type MockPartnerService struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerServiceMockRecorder
	isgomock struct{}
}

// MockPartnerServiceMockRecorder is the mock recorder for MockPartnerService.
type MockPartnerServiceMockRecorder struct {
	mock *MockPartnerService
}

// NewMockPartnerService creates a new mock instance.
func NewMockPartnerService(ctrl *gomock.Controller) *MockPartnerService {
	mock := &MockPartnerService{ctrl: ctrl}
	mock.recorder = &MockPartnerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerService) EXPECT() *MockPartnerServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPartnerService) Create(ctx context.Context, partner domain.Partner) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, partner)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPartnerServiceMockRecorder) Create(ctx, partner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPartnerService)(nil).Create), ctx, partner)
}

// CreateBatch mocks base method.
func (m *MockPartnerService) CreateBatch(ctx context.Context, file io.Reader, createdBy string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, file, createdBy)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockPartnerServiceMockRecorder) CreateBatch(ctx, file, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockPartnerService)(nil).CreateBatch), ctx, file, createdBy)
}

// Delete mocks base method.
func (m *MockPartnerService) Delete(ctx context.Context, partnerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, partnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPartnerServiceMockRecorder) Delete(ctx, partnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPartnerService)(nil).Delete), ctx, partnerID)
}

// GetByID mocks base method.
func (m *MockPartnerService) GetByID(ctx context.Context, partnerID string) (*domain.Partner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, partnerID)
	ret0, _ := ret[0].(*domain.Partner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPartnerServiceMockRecorder) GetByID(ctx, partnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPartnerService)(nil).GetByID), ctx, partnerID)
}

// Search mocks base method.
func (m *MockPartnerService) Search(ctx context.Context, filters domain.PartnerFilters) (domain.PagingResult[domain.Partner], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filters)
	ret0, _ := ret[0].(domain.PagingResult[domain.Partner])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPartnerServiceMockRecorder) Search(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPartnerService)(nil).Search), ctx, filters)
}

// Update mocks base method.
func (m *MockPartnerService) Update(ctx context.Context, partnerID string, editPartner domain.EditPartner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, partnerID, editPartner)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPartnerServiceMockRecorder) Update(ctx, partnerID, editPartner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPartnerService)(nil).Update), ctx, partnerID, editPartner)
}
