package domain

var regions = map[string]int{
	"Acre":                1,
	"Alagoas":             1,
	"Amapá":               1,
	"Amazonas":            1,
	"Bahia":               1,
	"Ceará":               1,
	"Distrito Federal":    1,
	"Espírito Santo":      1,
	"Goiás":               1,
	"Maranhão":            1,
	"Mato Grosso":         1,
	"Mato Grosso do Sul":  1,
	"Minas Gerais":        1,
	"Pará":                1,
	"Paraíba":             1,
	"Paraná":              1,
	"Pernambuco":          1,
	"Piauí":               1,
	"Rio de Janeiro":      1,
	"Rio Grande do Norte": 1,
	"Rio Grande do Sul":   1,
	"Rondônia":            1,
	"Roraima":             1,
	"Santa Catarina":      1,
	"São Paulo":           1,
	"Sergipe":             1,
	"Tocantins":           1,
}
