package domain

var regions = map[string]int{
	"Acre":                6,
	"Alagoas":             2,
	"Amapá":               6,
	"Amazonas":            5,
	"Bahia":               4,
	"Ceará":               3,
	"Distrito Federal":    3,
	"Espírito Santo":      6,
	"Goiás":               3,
	"Maranhão":            6,
	"Mato Grosso":         6,
	"Mato Grosso do Sul":  6,
	"Minas Gerais":        6,
	"Pará":                6,
	"Paraíba":             6,
	"Paraná":              0,
	"Pernambuco":          3,
	"Piauí":               6,
	"Rio de Janeiro":      6,
	"Rio Grande do Norte": 6,
	"Rio Grande do Sul":   4,
	"Rondônia":            6,
	"Roraima":             6,
	"Santa Catarina":      2,
	"São Paulo":           1,
	"Sergipe":             6,
	"Tocantins":           6,
}
